before_script:
  - cp spec/dummy/config/database.peak_flow.yml spec/dummy/config/database.yml
  - cd spec/dummy && bundle exec rake db:create db:environment:set db:schema:load RAILS_ENV=test && cd ..
rvm: true
services:
  postgres:
    environment:
      POSTGRES_USER: "build"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "active_record_query_fixer_test"
    expose:
      - 5432
    image: postgres:11.4
script:
  - bundle exec rspec
  - bundle exec rake best_practice_project:run
