before_script:
  - cp spec/dummy/config/database.peak_flow.yml spec/dummy/config/database.yml
  - cd spec/dummy && bundle exec rails db:create db:environment:set db:schema:load
rvm: true
services:
  postgres:
    environment:
      POSTGRES_USER: "build"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "active_record_query_fixer_test"
    expose:
      - 5432
    image: postgres:11.4
builds:
  build_1:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_2_rails_6.gemfile
      RUBY_VERSION: 2.7.8
    name: Ruby 2.7.8, Rails 6
    script:
      - bundle exec appraisal "ruby 2 rails 6" rspec
  build_2:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_2_rails_7.gemfile
      RUBY_VERSION: 2.7.8
    name: Ruby 2.7.8, Rails 7
    script:
      - bundle exec appraisal "ruby 2 rails 7" rspec
  build_3:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_3_rails_6.gemfile
      RUBY_VERSION: 3.2.2
    name: Ruby 3.2.2, Rails 6
    script:
      - bundle exec appraisal "ruby 3 rails 6" rspec
  build_4:
    environment:
      BUNDLE_GEMFILE: /home/build/project/gemfiles/ruby_2_rails_7.gemfile
      RUBY_VERSION: 3.2.2
    name: Ruby 3.2.2, Rails 7
    script:
      - bundle exec appraisal "ruby 3 rails 7" rspec
  build_5:
    name: Linters
    script:
      - bundle exec rake best_practice_project:run